apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels.service | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- toYaml .Values.labels.pod | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.containerPort }}
      name: http
